# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 100

  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 100
    cooldown:
      default-days: 10
    ignore:
      - dependency-name: 'adafruit-circuitpython-*'
      - dependency-name: 'circuitpython-stubs'
