[project]
name = "qtpy-datalogger"
version = "1.0.14"
description = "A remote control and data acquisition system using Adafruit QT Py S3"
readme = "README.md"
requires-python = ">=3.11,<4.0"
license = "Apache-2.0"
authors = [
    {name = "Down to the Wire", email = "all.wired.down@gmail.com"},
]
keywords = [
    "acquisition",
    "circuitpython",
    "control",
    "daq",
    "qtpy",
    "remote",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: Software Development :: User Interfaces",
]
dependencies = [
    # Host
    "beautifulsoup4>=4.14.3",
    "circup>=3.0.1",
    "click>=8.3.2",
    "findimports>=3.0.0",
    "gmqtt>=0.7.0",
    "matplotlib>=3.10.8",
    "packaging>=26.1",
    "pandas>=3.0.2",
    "psutil>=7.2.2",
    "pyserial>=3.5",
    "tksvg>=0.7.4",
    "ttkbootstrap>=1.20.2",
    "ttkbootstrap-icons>=4.0.0",
    "ttkbootstrap-icons-fa>=1.0.2",
    "wmi>=1.5.1",

    # sensor_node
    "circuitpython-stubs==9.2.1",
    "adafruit-circuitpython-adxl37x>=1.2.4",
    "adafruit-circuitpython-connectionmanager>=3.1.4",
    "adafruit-circuitpython-minimqtt>=8.0.0",
    "adafruit-circuitpython-neopixel>=6.3.16",
]

[project.urls]
Changelog = "https://github.com/wireddown/qtpy-datalogger/releases"
Documentation = "https://wireddown.github.io/qtpy-datalogger/develop/"
Homepage = "https://wireddown.github.io/qtpy-datalogger/"
Issues = "https://github.com/wireddown/qtpy-datalogger/issues"
Source = "https://github.com/wireddown/qtpy-datalogger"

[project.scripts]
qtpy-datalogger = "qtpy_datalogger.__main__:main"

[dependency-groups]
dev = [
    "mkdocstrings-python>=2.0.3",
    "poethepoet>=0.45.0",
    "pytest>=9.0.2",
    "ruff>=0.15.11",
    "ty>=0.0.37",
    "zensical>=0.0.33",
]

[tool.poe.tasks]
_ruff_check = "uv run ruff check"
_ruff_diff = "uv run ruff format --diff"
_ty_check = "uv run ty check --output-format concise"
_ruff_check_fix = "uv run ruff check --fix"
_ruff_format = "uv run ruff format"
_ty_check_fix = "uv run ty check --fix"
lint.help = "Run the analyzers for the package."
lint.sequence = ["_ruff_check", "_ruff_diff", "_ty_check"]
lint.ignore_fail = "return_zero"
fix.help = "Run the code formatters on the package."
fix.sequence = ["_ruff_check_fix", "_ruff_format", "_ty_check_fix"]
fix.ignore_fail = "return_zero"
test.help = "Run the tests for the package."
test.cmd = "pytest"
_generate_notice = "uv run qtpy-datalogger --verbose --generate-notice ./src/qtpy_datalogger/sensor_node/snsr/notice.toml"
_build_dist = "uv build --verbose"
build.sequence = ["_generate_notice", "_build_dist"]
build.help = "Build the package for release."
_reset_license = "git checkout HEAD -- docs/license.md"
_prime_license.shell = "cat LICENSE >> docs/license.md"
_build_docs = "uv run zensical build --clean"
docs.help = "Build the documentation site."
docs.sequence = ["_reset_license", "_prime_license", "_build_docs"]

[tool.pytest]
addopts = [
    "--showlocals",
    "--durations=20",
]

[tool.ty.analysis]
respect-type-ignore-comments = false  # Disable support for `type: ignore` comments

[tool.ty.rules]
all = "error"
"missing-override-decorator" = "ignore"  # Available in Python 3.12

# Submodule snsr.pysh uses PC-only imports to help with development and testing
[[tool.ty.overrides]]
include = ["src/qtpy_datalogger/sensor_node/snsr/pysh/**"]

[tool.ty.overrides.rules]
possibly-unresolved-reference = "ignore"

# Submodule snsr.node.classes uses loose typing rather than full classes to support CircuitPython json constraints
[[tool.ty.overrides]]
include = ["src/qtpy_datalogger/sensor_node/snsr/node/classes.py"]

[tool.ty.overrides.rules]
invalid-argument-type = "ignore"
invalid-return-type = "ignore"

# Do not leave suppressions in example code which might be used in projects that use other type checkers
[[tool.ty.overrides]]
include = ["examples"]

[tool.ty.overrides.rules]
invalid-argument-type = "ignore"

[tool.ty.src]
exclude = [
    "docs/legacy",
]

[tool.ruff]
line-length = 120
extend-exclude = [
    "docs/legacy",
]

[tool.ruff.lint]
extend-select = [
    "A",
    "ANN",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "COM",
    "D",
    "DTZ",
    "EM",
    "ERA",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "NPY",
    "PD",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "Q",
    "RET",
    "RUF",
    "S",
    "SIM",
    "T10",
    "T20",
    "TD",
    "TRY",
    "UP",
    "W",
]
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
    "COM812",
    "D203",
    "D211",
    "D212",
    "D400",
    "G004",
    "ISC001",
    "RET504",
    "TD002",
]

# Disable rules by path
[tool.ruff.lint.per-file-ignores]
# Tests
"tests/**.py" = [
    "INP001",       # Allow implicit namespaces
    "PLC0415",      # Allow non-toplevel imports for clarity
    "S101",         # Allow the 'assert' keyword
]
# Examples
"examples/**.py" = [
    "C401",         # Allow unnecessary generators to support explicit initialization
    "INP001",       # Examples are not namespace packages and don't use __init__.py either
    "PLR0912",      # Allow many if/else branches to support feature demonstrations
    "PLR0915",      # Allow long functions for detailed unoptimized demonstrations
]
# Templates
"src/qtpy_datalogger/apps/empty.py" = [
    "F401",         # Allow unused imports for the template
]
# CircuitPython
# - Some Python libraries are not available on CircuitPython
# - Some design pattern deviations are expected
"src/qtpy_datalogger/sensor_node/**.py" = [
    "INP001",       # No __init__.py because code.py is the entry point
    "PLC0415",      # Allow non-toplevel imports to conserve memory
    "PLR2004",      # Allow "magic number" literals to conserve memory
    "PTH116",       # Path.stat() is not available
    "PTH123",       # Path.open() is not available
    "PTH208",       # Path.iterdir() is not available
    "SIM105",       # contextlib is not available
    "T201",         # Use direct IO for user REPL
]

[build-system]
requires = [
    "uv_build>=0.11.11,<0.12.0",
]
build-backend = "uv_build"
