name: 'CI: Tests and Analyzers'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Test on Python ${{ matrix.python_version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [
          '3.11',
          '3.12',
          '3.13',
          '3.14',
        ]

    steps:
    - name: Get source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        echo '# :shield: Python ${{ matrix.python_version }}: Run Tests and Analyzers' >> $env:GITHUB_STEP_SUMMARY
        echo '_(run ${{ github.run_number }} attempt ${{ github.run_attempt }})_' >> $env:GITHUB_STEP_SUMMARY
        uv lock --check
        uv sync --verbose
        echo '## :package: Installed plugins and dependencies' >> $env:GITHUB_STEP_SUMMARY
        echo "Using" >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv self version >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        echo "for this run." >> $env:GITHUB_STEP_SUMMARY
        echo '<details>' >> $env:GITHUB_STEP_SUMMARY
        echo '<summary> :package: <strong>Run-time</strong> dependencies</summary>' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv tree --no-dev >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '</details>' >> $env:GITHUB_STEP_SUMMARY
        echo '<details>' >> $env:GITHUB_STEP_SUMMARY
        echo '<summary> :building_construction: <strong>Build-time</strong> dependencies</summary>' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv tree --only-dev >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '</details>' >> $env:GITHUB_STEP_SUMMARY

    - name: Run pytest
      run: uv run pytest --verbose --junit-xml=junit/pytest-results-py${{ matrix.python_version }}-${{ runner.os }}.xml

    - name: Run ruff check
      id: ruff-check
      run: |
        uv run ruff check --output-format github
        uv run ruff check --output-format junit --output-file junit/ruff-check-results-py${{ matrix.python_version }}-${{ runner.os }}.xml
      if: always()

    - name: Run ruff format
      id: ruff-format
      run: |
        uv run ruff format --check
      if: always()

    - name: Run ruff format --diff
      run: |
        uv run ruff format --diff
        echo '## :microscope: ruff check errors' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '### Lint rule errors' >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv run ruff check --output-format grouped >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        echo 'If there are errors:' >> $env:GITHUB_STEP_SUMMARY
        echo '- :green_circle: Use `uv run poe fix` to apply safe fixes' >> $env:GITHUB_STEP_SUMMARY
        echo '- :warning: Use `uv run ruff check --fix --unsafe-fixes` to apply experimental fixes' >> $env:GITHUB_STEP_SUMMARY
        echo '- :book: Use `uv run ruff rule Z123 | mdv -` to see examples' >> $env:GITHUB_STEP_SUMMARY
        echo '  - `mdv` is a [terminal viewer](https://github.com/axiros/terminal_markdown_viewer) for markdown' >> $env:GITHUB_STEP_SUMMARY
        echo '  - Full list on https://docs.astral.sh/ruff/rules/' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '### Format errors' >> $env:GITHUB_STEP_SUMMARY
        echo '```diff' >> $env:GITHUB_STEP_SUMMARY
        uv run ruff format --diff 2>&1 >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        echo 'If there are errors:' >> $env:GITHUB_STEP_SUMMARY
        echo ' - :green_circle: Use `uv run ruff format` to fix errors' >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
      if: ${{ failure() && (steps.ruff-check.conclusion == 'failure' || steps.ruff-format.conclusion == 'failure') }}
      continue-on-error: true

    - name: Run ty
      run: |
        uv run ty check --python-version ${{ matrix.python_version }} --output-format github --verbose
        uv run ty check --python-version ${{ matrix.python_version }} --output-format junit >> junit/ty-check-results-py${{ matrix.python_version }}-${{ runner.os }}.xml
        echo '## :microscope: ty results' >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv run ty check --python-version ${{ matrix.python_version }} --output-format concise >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
      if: always()

    - name: Create result report
      id: result-report
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2  # v3.0.0
      with:
        name: Results for Python ${{ matrix.python_version }} on ${{ runner.os }}
        path: junit/*.xml
        reporter: 'java-junit'
        fail-on-error: false
      if: always()

    - name: Get report ID
      run: |
        $report_id_segment = '${{steps.result-report.outputs.url}}'.split('/')[-1]
        echo "REPORT_ID=$report_id_segment" >> $env:GITHUB_ENV
      if: always()

    - name: Build package
      run: uv run poe build
      if: always()

    - name: Upload source package
      id: upload-source-package
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: qtpy-datalogger-py${{ matrix.python_version }}-${{ runner.os }}-source
        path: dist/*.tar.gz
      if: always()

    - name: Upload wheel package
      id: upload-wheel-package
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: qtpy-datalogger-py${{ matrix.python_version }}-${{ runner.os }}-wheel
        path: dist/*.whl
      if: always()

    - name: Build documentation
      run: uv run poe docs
      if: always()

    - name: Upload documentation
      id: upload-doc-site
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: qtpy-datalogger-documentation-site-py${{ matrix.python_version }}-${{ runner.os }}
        path: site/
      if: always()

    - name: Write workflow summary
      run: |
        echo "## :test_tube: [Combined results](https://github.com/${{github.repository}}/runs/$($env:REPORT_ID)?check_suite_focus=true) :small_blue_diamond: ${{ steps.result-report.outputs.passed }} :white_check_mark: :small_blue_diamond: ${{ steps.result-report.outputs.failed }} :x: :small_blue_diamond: ${{ steps.result-report.outputs.skipped }} :next_track_button:" >> $env:GITHUB_STEP_SUMMARY
        echo '' >> $env:GITHUB_STEP_SUMMARY
        echo '## :arrow_down: Download [the package](${{ steps.upload-wheel-package.outputs.artifact-url }})' >> $env:GITHUB_STEP_SUMMARY
        echo '## :green_book: Download [the documentation](${{ steps.upload-doc-site.outputs.artifact-url }})' >> $env:GITHUB_STEP_SUMMARY
      if: always()
