name: 'Docs: Build and Publish'

on:
  workflow_dispatch:
    inputs:
      force_publish_override:
        description: 'Publish the documentation from this run'
        required: false
        type: boolean
  release:
    types: [ published ]

jobs:
  build:
    name: Build documentation site
    runs-on: windows-latest
    steps:
    - name: Get source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        python-version: '3.11'
        enable-cache: false

    - name: Install dependencies
      run: |
        echo '# :books: Build docs _(run ${{ github.run_number }} attempt ${{ github.run_attempt }})_' >> $env:GITHUB_STEP_SUMMARY
        uv lock --check
        uv sync --verbose
        echo '## :package: Installed plugins and dependencies' >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv self version >> $env:GITHUB_STEP_SUMMARY
        uv tree --no-dev >> $env:GITHUB_STEP_SUMMARY
        uv tree --only-dev >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY

    - name: Build documentation
      run: uv run poe docs

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: site/

  publish:
    name: Publish to Pages
    if: github.event_name == 'release' || inputs.force_publish_override
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy doc site
      id: deployment
      uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
