name: 'Publish: Release on PyPI'

on:
  workflow_dispatch:
    inputs:
      release_tag_override:
        # Use this input for previewing or debugging the workflow
        # Publishing to PyPI still requires a GitHub release event to start this workflow
        description: 'Override the release tag: M.m.u'
        required: true
        type: string
  release:
    types: [ published ]

jobs:
  build:
    name: Build distribution packages
    runs-on: windows-latest
    steps:
    - name: Get source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: '3.11'
        enable-cache: false

    - name: Install dependencies
      run: |
        echo '# :flying_saucer: Release on PyPI _(run ${{ github.run_number }} attempt ${{ github.run_attempt }})_' >> $env:GITHUB_STEP_SUMMARY
        uv lock --check
        uv sync --verbose
        echo '## :package: Installed plugins and dependencies' >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY
        uv self version >> $env:GITHUB_STEP_SUMMARY
        uv tree --no-dev >> $env:GITHUB_STEP_SUMMARY
        uv tree --only-dev >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY

    - name: Confirm release coherence
      run: |
        import json
        import packaging.version
        import subprocess

        tag_name = "${{ inputs.release_tag_override }}" or "${{ github.event.release.tag_name }}"
        error_messages = []
        print(f"Checking release tag name {tag_name}")

        # Confirm the release tag version matches the package version
        tag_version = packaging.version.Version(tag_name)
        str_version = subprocess.check_output(["uv", "version", "--short"]).strip().decode()
        pkg_version = packaging.version.Version(str_version)
        if tag_version != pkg_version:
            error_messages.append(f"Version mismatch: tag is {tag_version} and package is {pkg_version}")

        # Confirm the releasing version hasn't been published already
        released_text = subprocess.check_output(["curl", "-s", "https://pypi.org/pypi/qtpy-datalogger/json"]).strip().decode()
        released_json = json.loads(released_text)
        released_dicts = released_json.get("releases", {})
        released_versions = sorted([packaging.version.Version(key) for key in released_dicts], reverse=True)
        if pkg_version in released_versions:
            error_messages.append(f"Version collision: version {pkg_version} is already published")

        if error_messages:
            exit_message = "\n".join(error_messages)
            raise ValueError(exit_message)
      shell: uv run python {0}

    - name: Build package
      run: |
        echo '# :building_construction: Build distribution packages' >> $env:GITHUB_STEP_SUMMARY
        uv run poe build
        echo '## notice.toml' >> $env:GITHUB_STEP_SUMMARY
        echo '```toml' >> $env:GITHUB_STEP_SUMMARY
        cat src\qtpy_datalogger\sensor_node\snsr\notice.toml >> $env:GITHUB_STEP_SUMMARY
        echo '```' >> $env:GITHUB_STEP_SUMMARY

    - name: Upload release packages
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: release-distribution-packages
        path: dist/

  publish:
    name: Publish to PyPI
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/qtpy-datalogger
    permissions:
      id-token: write
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: release-distribution-packages
        path: dist/
    - name: 'Upload to PyPI'
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
    - run: |
        echo '# :snake: Upload to PyPI' >> $GITHUB_STEP_SUMMARY
        echo '## Version ${{ github.event.release.tag_name }} published' >> $GITHUB_STEP_SUMMARY
        echo '## Release history' >> $GITHUB_STEP_SUMMARY
        echo '- https://pypi.org/project/qtpy-datalogger/#history' >> $GITHUB_STEP_SUMMARY
        ls -lR dist

  update_version:
    name: Update version
    runs-on: windows-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Get source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: '3.11'
        enable-cache: false

    - name: Install dependencies
      run: |
        echo '# :sparkle: Update package version' >> $env:GITHUB_STEP_SUMMARY
        uv lock --check
        uv sync --verbose

    - name: Update package version
      id: update_version
      run: |
        $new_version = $(uv version --short --bump patch)
        echo "new_version=$new_version" >> $env:GITHUB_OUTPUT
        echo "## New version: $new_version" >> $env:GITHUB_STEP_SUMMARY

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        base: "${{ github.event_name == 'release' && github.event.release.target_commitish || github.ref_name }}"
        branch: 'users/build/update-package-version-to-${{ steps.update_version.outputs.new_version }}'
        commit-message: 'Automated version update to ${{ steps.update_version.outputs.new_version }}'
        title: 'pyproject.toml: Update version to ${{ steps.update_version.outputs.new_version }}'
        body:  |
          This PR updates the package's version in `pyproject.toml` to **${{ steps.update_version.outputs.new_version }}**.

          Close and reopen this PR to start the PR checks.

          _Automated:_ See [.github/workflows/publish.yml](${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/publish.yml) for details.

    - name: Write summary
      run: |
        echo '## Pull request' >> $env:GITHUB_STEP_SUMMARY
        echo '- ${{ steps.create_pr.outputs.pull-request-url }}' >> $env:GITHUB_STEP_SUMMARY
